config/routes.rb
Rails.application.routes.draw do
  root  'posts#index'
  
  devise_for :users

  resources :posts
  resources :teams
  resources :users
  resources :facts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fact.rb
class Fact < ApplicationRecord

  validates :question, presence: true 

end

app/models/post.rb
class Post < ApplicationRecord

  validates :body, presence: true
  
end

app/models/team.rb
class Team < ApplicationRecord
  # Team 1 for teams
  TEAM_1 = "team_1"

  # Team 2 for teams
  TEAM_2 = "team_2"

  # Team 3 for teams
  TEAM_3 = "team_3"

  # Team 4 for teams
  TEAM_4 = "team_4"

  # Team 5 for teams
  TEAM_5 = "team_5"

  # Unassigned for teams
  UNASSIGNED = "unassigned"

  validates :name, presence: true

  # returns team_2 id for droppzone
  def self.team_1
    find_by(name: TEAM_1)
  end

  # returns team_3 id for droppzone
  def self.team_2
    find_by(name: TEAM_2)
  end

  # returns team_4 id for droppzone
  def self.team_3
    find_by(name: TEAM_3)
  end

  # returns team_5 id for droppzone
  def self.team_4
    find_by(name: TEAM_4)
  end

  # returns team_5 id for droppzone
  def self.team_5
    find_by(name: TEAM_5)
  end

  # returns team_5 id for droppzone
  def self.unassigned
    find_by(name: UNASSIGNED)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :by_team, ->(team) { joins(:team).where(teams: { name: team }) }

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  belongs_to :team
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private 
    def configure_permitted_parameters
    # for creating users
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name email password team_id
                                                         phone_number
                                                         password_confirmation current_password
]
    )
    # for updating users
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name email password team_id
                                                                 phone_number
                                                                password_confirmation
]
    )
  end
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  def index
    @facts = Fact.all
  end

  def create
    @fact = Fact.new(facts_param)
    if @fact.save 
      redirect_to facts_path
      flash[:success] = "Fact Created"
    else 
      flash[:error] = "Fact Not Created"
    end
  end

  def update
    @fact = Fact.find(params[:id])
    if @fact.update(facts_param)
      redirect_to facts_path
      flash[:success] = "Fact Updated"
    else
      flash[:error] = "Fact Not Updated"
    end
  end

  def edit
    @fact = Fact.find(params[:id])
  end

  def destroy
    @fact = Fact.find(params[:id])
    if @fact.destroy
      redirect_to root_path
      flash[:success] = "Fact Destroyed"
    else 
      flash[:error] = "Fact Not Destroyed"
    end 
  end

  def show
    @fact = Fact.find(params[:id])
  end

  private 

  def facts_param
    params.require(:fact).permit(:answer, :question)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order(created_at: :desc).all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save 
      redirect_to root_path
      flash[:success] = "Post Created"
    else 
      flash[:error] = "Post Not Created"
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
      flash[:success] = "Post Updated"
    else
      flash[:error] = "Post Not Updated"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to root_path
      flash[:success] = "Post Destroyed"
    else 
      flash[:error] = "Post Not Destroyed"
    end 
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @unassigned = fetch_unassigned
    @team_1 = fetch_team_0
    @team_2 = fetch_team_1
    @team_3 = fetch_team_2
    @team_4 = fetch_team_3
    @team_5 = fetch_team_4
  end

  def update
    @team = Team.find(params[:id])
    if @team.update(team_params)
      redirect_to teams_path
      flash[:success] = "team Updated"
    else
      flash[:error] = "team Not Updated"
    end
  end

  private 

  def team_params
    params.require(:team).permit(:name)
  end

  def all_users 
    User.includes(:team)
  end

  def fetch_unassigned
    all_users.by_team("unassigned")
  end

  def fetch_team_0
    all_users.by_team("team_1")
  end

  def fetch_team_1
    all_users.by_team("team_2")
  end

  def fetch_team_2
    all_users.by_team("team_3")
  end

  def fetch_team_3
    all_users.by_team("team_4")
  end

  def fetch_team_4
    all_users.by_team("team_5")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to teams_path
    else
      redirect_to teams_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    byebug
    @user = User.find(params[:id])
    @user.email = current_user.email

    if @user.update(user_params)
      redirect_to teams_path
    else
      
    end
  end

  private

  def user_params
    params.require(:user).permit(:team_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
      case level
          when :notice then "alert alert-info"
          when :success then "alert alert-success"
          when :error then "alert alert-error"
          when :alert then "alert alert-error"
      end
  end
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/facts/_fact.html.erb
<div class="card border border-primary">
  <div class="card-body border border-primary">
    <h6>Question number <%= fact.id %></h6>
      Q: <%= fact.question %>
    <br />
    <hr class="border border-primary" />
    <% if fact.answer.present? %>
      A: <%= fact.answer %>
    <% else  %>
      <%= form_with( model: Fact.new, url: fact_path(id: fact.id), method: :patch ) do |f| %>
        <%= f.text_field :answer, class: "w-100 p-2 rounded-pill post-input mt-2" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/facts/index.html.erb
<div class="container">
  <h4 class="text-center">Frequently asked questions</h4>
  <h6 class="text-center">Before posting a question please make sure the question does not exist</h6>
  <h6 class="text-center">Write your questions in the input box below.  Press enter to submit the question</h6>
  <div class="col-md-12">
    <%= form_with model: Fact.new do |f| %>
      <%= f.text_field :question, class: "w-100 p-2 rounded-pill post-input mt-2" %>
    <% end %>
  <div>

  <div class="container">
    <h4 class="text-center mt-3">Lists of Questions</h4>
    <%= render @facts %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamManagement</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="w-100 vh-100">
      <head>
        <%= render 'shared/navbar' %>
      </head>
      <div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: Post.new do |f| %>
  <div class="row d-flex justify-content-between">
    <div class="col-md-12">
      <%= f.text_field :body, class: "w-100 p-2 rounded-pill post-input", placement: "Write a post here"  %>
    </div>
  </div>
<% end %>

app/views/posts/_new.html.erb
<div class="modal-header d-flex justify-content-between">
  <h2 class="modal-title font-weight-bold text-2xl" id="new-client-modal-title">Add New Announcement</h2>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <%= render 'form' %>
</div>

app/views/posts/_post.html.erb
<div class="card border border-primary mt-2 mb-2">
  <div class="card-body border border-primary">
   <%= post.id %> : <%= post.body %>
  </div>
</div>

app/views/posts/index.html.erb
<% if current_user.id == 1 %>
  <div class="container">
      <%= link_to 'Add Announcement', new_post_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  %>
  </div>
<% else %>
  <div class="container">
      <h4>Announcements and Home Work</h4>
  </div>
<% end %>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

<div class="container">
  <%= render @posts %>
</div>

app/views/posts/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
      <%= value %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if current_user %>
  <nav class="navbar navbar-expand-lg navbar-light"  style="background-color: #e3f2fd;">
    <%= link_to  "Hmonglish", posts_path, style: "font-family: 'Lobster', cursive;  font-size: 25px;", class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNav">
      <ul class="navbar-nav ">
        <li class="nav-item active">
          <%= link_to  "Announcements", posts_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Teams", teams_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to  "Frequent Questions", facts_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to edit_user_registration_path, class: 'nav-link', id: 'edit-user-link' do %>
            <span class="text-teal-600 text-sm">Logged in as: <%= current_user.first_name %></span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link", :data => { :no_turbolink => true } %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>